config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'scores#index'
  get '/highscores', to: 'scores#csv'
  post '/submit_score', to: 'scores#submit_score'
  resources :players, only: [:index, :show], :id => /.*/
  resources :versions, only: [:index, :show], :id => /.*/
  get '/signup', to: 'players#new'
  get '/get_auth_token', to: 'players#get_auth_token'
  post '/players', to: 'players#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :scores
  has_secure_token :auth_token # Authentication token for submitting highscores.
  has_secure_password
  validates :password, length: { minimum: 6 }
  validates :name, uniqueness: true, presence: true

  def attnam_link
    "https://attnam.com/users/" + attnam_username if attnam_username
  end

  def to_param
    name
  end
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :player, optional: true
  belongs_to :version
  validates :points, :character, :entry, presence: true
  validates :points, numericality: { greater_than: 0 }

  def self.sorted(filter = {})
    Score.where(filter).order(points: :desc)
  end
end

app/models/version.rb
class Version < ApplicationRecord
  has_many :scores
  validates_uniqueness_of :string

  def to_param
    string
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  end
  
  def show
    @player = Player.find_by_name(params[:id])
    @scores = Score.sorted(player: @player)
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to root_url, notice: 'Player created.'
    else
      render :new
    end
  end

  def get_auth_token
    player = authenticate_with_http_basic do |username, password|
      Player.find_by(name: username)&.authenticate(password)
    end

    if player
      render plain: player.auth_token
    else
      request_http_basic_authentication
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :attnam_username, :password, :password_confirmation)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @scores = Score.sorted
  end

  def csv
    csv_string = Score.sorted.map { |s| "\n#{s.points},\"#{s.character}, #{s.entry}\"" }.join
    render plain: csv_string
  end

  def submit_score
    player = Player.find_by(name: params[:username],
                            auth_token: params[:auth_token])
    character, entry = params[:entry].split(", ", 2)
    version = Version.find_or_create_by(string: params[:version])
    score = Score.new(player: player, points: params[:score], character: character,
                      entry: entry, version: version)
    head(score.save ? :ok : :bad_request)
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def index
  end

  def show
    @version = Version.find_by_string(params[:id])
    @scores = Score.sorted(version: @version)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IVAN Hall of Fame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Scores', root_path %>
      <%= link_to 'Players', players_path %>
      <%= link_to 'Versions', versions_path %>
      <%= link_to 'Sign up', signup_path %>
    </nav>
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2>Could not sign up because of the following errors:</h2>
      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @player.new_record? %>
    <div class="field">
      <%= f.label :name, "Username" %>
      <%= f.text_field :name %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attnam_username, "Attnam.com username" %>
    <%= f.text_field :attnam_username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/index.html.erb
<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Attnam profile</th>
    </tr>
  </thead>
  <tbody>
    <% for player in Player.all %>
      <tr>
        <td><%= link_to player.name, player %></td>
        <% if player.attnam_username %>
          <td><%= link_to player.attnam_username, player.attnam_link %></td>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<h1>Sign up</h1>

<%= render 'form', player: @player %>

app/views/players/show.html.erb
<h1><%= @player.name %>'s Scores</h1>

<%= render "scores/table" %>

app/views/scores/_table.html.erb
<div id="score-table">

<table>
  <thead>
    <tr>
      <th></th>
      <th class="sort" data-sort="rank">Score</th>
      <th class="sort" data-sort="character">Character</th>
      <th class="sort" data-sort="ending">Ending</th>
      <th class="sort" data-sort="player">Player</th>
      <th class="sort" data-sort="version">Version</th>
      <th class="sort" data-sort="date">Date</th>
    </tr>
  </thead>
  <tbody class="list">
    <% for score, rank in @scores.each_with_index %>
      <tr>
        <td class="rank"><%= rank + 1 %></td>
        <td class="score"><%= number_with_delimiter(score.points) %></td>
        <td class="character"><%= score.character %></td>
        <td class="ending"><%= score.entry %></td>
        <% if score.player %>
          <td class="player"><%= link_to score.player.name, score.player  %></td>
        <% else %>
          <td class="player" title="unregistered player">?</td>
        <% end %>
        <td class="version"><%= link_to score.version.string, score.version if score.version %></td>
        <td>
          <span class="date" title="<%= score.created_at %>">
            <%= score.created_at.strftime("%F") %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<script type="text/javascript">
  var options = {
    valueNames: ['rank', 'score', 'character', 'ending', 'player', 'version', 'date']
  };
  var scores = new List('score-table', options);
  scores.sort('rank', { order: 'asc' }); // Register active column.
</script>

app/views/scores/index.html.erb
<h1><span>Iter Vehemens ad Necem</span> <span>Hall of Fame</span></h1>

<%= render "scores/table" %>

app/views/versions/index.html.erb
<h1>Versions</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th>Scores submitted</th>
    </tr>
  </thead>
  <tbody>
    <% for version in Version.all %>
      <tr>
        <td><%= link_to version.string, version %></td>
        <td><%= version.scores.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/versions/show.html.erb
<h1><%= @version.string %> Scores</h1>

<%= render "scores/table" %>